import type { Metadata } from "next";
import "./globals.css";
import { Header, Footer } from "@/components";
import LenisContext from "@/context/LenisContext";

export const metadata: Metadata = {
  title: "itsthewestend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LenisContext>
      <html lang="en">
        <body className="bg-bridal-health text-trace-ash">
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </LenisContext>
  );
}
